// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy7yCQGDqkZpiw_Q5NcZCZ0riEmzQAOWM',
    appId: '1:909805744262:web:03e5968c51c0ee62b32107',
    messagingSenderId: '909805744262',
    projectId: 'gigs-court',
    authDomain: 'gigs-court.firebaseapp.com',
    storageBucket: 'gigs-court.firebasestorage.app',
    measurementId: 'G-P9Q80180LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAetuMTWvRVASK01pyQxMgs5C9mbqdIReo',
    appId: '1:909805744262:android:6d7dccc5c464c754b32107',
    messagingSenderId: '909805744262',
    projectId: 'gigs-court',
    storageBucket: 'gigs-court.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCljRLmO7F3CFreyoGlYVFrLeCqqyoSCxE',
    appId: '1:909805744262:ios:804fcc5b9499bdd9b32107',
    messagingSenderId: '909805744262',
    projectId: 'gigs-court',
    storageBucket: 'gigs-court.firebasestorage.app',
    iosBundleId: 'com.example.gigscourt',
  );
}
